version "4.0"

#include "zscript/base.zs"
#include "zscript/mixins.zs"
#include "zscript/event.zs"

#include "zscript/zomb.zs"
#include "zscript/imp.zs"
#include "zscript/shotty.zs"
#include "zscript/cyberzerker.zs"
#include "zscript/porkchop.zs"
#include "zscript/soulborg.zs"
#include "zscript/terminator.zs"
#include "zscript/foofighter.zs"
#include "zscript/ravager.zs"
#include "zscript/hunter.zs"
#include "zscript/skull.zs"